meta_product_name: "Carotte ta Coloc"
meta_title: "Carotte Ta Coloc - Quand le ménage devient un jeu !"
meta_description: "Une application pour organiser les tâches ménagères entre coloc"
meta_image: "logo.png" # should exist in `app/assets/images/`

